### ISSUE TITLE
Improved static files management

### ISSUE THREAD

**Issue by amercader** [ckan/ideas#95]
<a href="https://github.com/rshk"><img src="https://avatars.githubusercontent.com/u/434561?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rshk](https://github.com/rshk)**
_Friday Nov 08, 2013 at 14:41 GMT_
_Originally opened as https://github.com/ckan/ckan/issues/1311_

---

While I understand why it's handy using something like fanstatic, especially for development, it has several issues:
- It forces static files to be served by the application, thus wasting more resources than if they were served directly by the webserver/proxy.
- It generates way too long urls, containing "bad" characters (like colons) too..
- Keeping creating bundles over and over is just a useless waste of resources
- Anyways, it itsn't used to properly minify / aggregate css and js files, which should be its main purpose
- That cache management system (infinite caching + urls containing datestamps) is just lame, there are http headers to do that the proper way, no need to reinvent the wheel.

IMHO we should try to figure out how to adopt something better, maybe similar to the django "staticfiles" application, that allows for a simple way of finding & serving static files (for development) and aggregating them in a single folder (for production).

Any thoughts?

**Comment by rufuspollock** [comment]
@amercader what's the status here? can we close as either FIXED or WONTFIX?

**Comment by rufuspollock** [comment]
@smotornyuk could you close this with an update of what happened 😄

**Comment by smotornyuk** [comment]
Starting from v2.9 we are using webassets instead of fanstatic. 

This update solves following problem and creates a space for future improvements(maybe, in the upcoming patch releases after v2.9):

* **With Fanstatic static files served by application** - with webassets one can use `ckan.webassets.use_x_sendfile` config option([XSendfile](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/) ) or intercept all the requests to `/webassets/..` and serve files using any suitable tool because all static files are stored in the filesystem, not generated in memory. 
* **Fanstatic generates way too long URLs, containing "bad" characters (like colons) too..** - Webassets generates nice URLs, like `/webassets/base/5f5a82bb_main.js` with hash of content in the filename, so you can just cache static files forever.
* **Fanstatic is keeping creating bundles over and over** - webassets creates bundles only when the bundle requested first time or source of bundle changed. You can prepare bundles using `ckan asset build` CLI command and they will never be recompiled if you are not changing source files. 
* webassets can preprocess\minify bundles with one of built-ins or external(requires installation) libraries
* **That cache management system (infinite caching + URLs containing datestamps) is just lame, there are HTTP headers to do that the proper way, no need to reinvent the wheel.** - this issue is not fixed. Personally, I'm more JS-dev, than python-dev and I'm quite used to caching based on content-hash injected in the filename(I'm always using `[name].[hash].js` output pattern in webpack and just love it). So I don't consider it as a "bad" strategy, but I don't mind if anyone will provide PR with improvements for the header-based cache.
